import type { AppProps } from 'next/app'
import Head from 'next/head'
import Footer from "../components/footer"
import Header from "../components/header"
import { createGlobalStyle } from "styled-components";
import { MoralisProvider } from "react-moralis";
import { ethers } from "ethers";
import { MORALIS_ID, MORALIS_URL } from '../constants';
import { Web3ReactProvider } from '@web3-react/core';
import AccountProvider from "../hooks/useAccount"

import "slick-carousel/slick/slick.css";
import "slick-carousel/slick/slick-theme.css";
import "react-loading-skeleton/dist/skeleton.css"
import 'react-tabs/style/react-tabs.css';

import { SkeletonTheme } from "react-loading-skeleton"

const getLibrary = (provider: any) => {
  const library = new ethers.providers.Web3Provider(provider)
  library.pollingInterval = 12000
  return library
}

const GlobalStyle = createGlobalStyle`
  html,
  body {
    padding: 0;
    margin: 0; 
  }

  body {
    font-family: -apple-system, BlinkMacSystemFont, Segoe UI, Roboto, Oxygen,
    Ubuntu, Cantarell, Fira Sans, Droid Sans, Helvetica Neue, sans-serif;
    color: white;
    background-color: #20283E;
    background-image:  url('/images/bg-2.png');
    background-size: 100%;
    min-height: 100vh;
    --main-color: #242582;
    --secondary-color: #553D67;
    --logo-color: #F64C72;
    --text-color: #99738E;
    --bg-color: #2F2FA2;
  }

  a {
    color: inherit;
    text-decoration: none;
    :hover {
      text-decoration: underline;
    }
  }

  * {
    box-sizing: border-box;
  }

`;


function MyApp({ Component, pageProps }: AppProps) {

  return (
    <>
      <Head>
        <title>We&rsquo;ll be back soon! </title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div>
        {/* <AccountProvider>
          <Web3ReactProvider getLibrary={getLibrary}>
            <MoralisProvider serverUrl={MORALIS_URL || ""} appId={MORALIS_ID || ""}>
              <SkeletonTheme highlightColor="#ccc">
                <GlobalStyle />
                <Header />
                <Component {...pageProps} />
                <Footer />
              </SkeletonTheme>
            </MoralisProvider>
          </Web3ReactProvider>
        </AccountProvider> */}
        <article style={{ textAlign: "center", marginTop: "10rem" }}>

          <h1>We&rsquo;ll be back soon!</h1>
          <div style={{ maxWidth: "800px", marginLeft: "auto", marginRight: "auto" }}>
            <p>Sorry for the inconvenience. We&rsquo;re performing some maintenance at the moment. If you need to you can always follow us on <a href="https://twitter.com/tamagofinance">Twitter</a> for updates, otherwise we&rsquo;ll be back up shortly!</p>
            <p>&mdash; The Tamago Team</p>
          </div>
        </article>
      </div>

    </>
  )
}

export default MyApp
